[package]
name = "libpuri"
version = "0.1.0"
authors = ["YujinGaya <yujin.gaya@gmail.com>"]
edition = "2018"
description = "Idiomatic Rust Competitive Programming Library"
documentation = "https://docs.rs/libpuri"
repository = "https://github.com/YujinGaya/libpuri"
license = ""

[dependencies]
